#!/bin/bash

#get all resources and length
all_resources=$(kubectl get all --all-namespaces -o json)
number_of_resources=$(echo $all_resources|jq ".items|length")
pointer_length=$((number_of_resources-1))

# loop through resource and check if argument passed in metadata name,labels or annotations
for pointer in $(seq 0 ${pointer_length}); do
    resource=$(echo $all_resources | jq ".items[${pointer}]")
    metadata=$(echo $resource|jq ".metadata")
    name=$(echo $metadata| jq ".name")
    labels=$(echo $metadata| jq ".labels")
    annotations=$(echo $metadata| jq ".annotations")
    if [[ $name =~ $1 ]] || [[ $labels =~ $1 ]] || [[ $annotations =~ $1 ]]; then
        kind=$(echo $resource | jq ".kind")
        namespace=$(echo $metadata| jq ".namespace")
        echo $namespace/$kind/$name
    fi
   
    
done
